// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj0sGOvoxxnaCCIJWwkQwnSHmbk-ZSqBc',
    appId: '1:814544311800:web:e1bd89da0da2f94db3b20d',
    messagingSenderId: '814544311800',
    projectId: 'flutter-login-app-70baa',
    authDomain: 'flutter-login-app-70baa.firebaseapp.com',
    storageBucket: 'flutter-login-app-70baa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfn40LTl5Foi_eOjLEMnKDVDDJGi55l20',
    appId: '1:814544311800:android:cbcfbf9414b59758b3b20d',
    messagingSenderId: '814544311800',
    projectId: 'flutter-login-app-70baa',
    storageBucket: 'flutter-login-app-70baa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgN8GY6VAfJkv4LeIOS0eMCB2cXKWNz7o',
    appId: '1:814544311800:ios:898fd4db92a3f1feb3b20d',
    messagingSenderId: '814544311800',
    projectId: 'flutter-login-app-70baa',
    storageBucket: 'flutter-login-app-70baa.appspot.com',
    androidClientId: '814544311800-75i4m2idova3m6el4q4pntocjb50mnei.apps.googleusercontent.com',
    iosClientId: '814544311800-ckfiio4taar9qlbqb5k8isdkuftiqlnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.application1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgN8GY6VAfJkv4LeIOS0eMCB2cXKWNz7o',
    appId: '1:814544311800:ios:898fd4db92a3f1feb3b20d',
    messagingSenderId: '814544311800',
    projectId: 'flutter-login-app-70baa',
    storageBucket: 'flutter-login-app-70baa.appspot.com',
    androidClientId: '814544311800-75i4m2idova3m6el4q4pntocjb50mnei.apps.googleusercontent.com',
    iosClientId: '814544311800-ckfiio4taar9qlbqb5k8isdkuftiqlnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.application1',
  );
}
